import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CoursesProvider } from '@/app/context/CourseContext';
import { InstancesProvider } from '@/app/context/InstanceContext';
import { Toaster } from 'sonner';
import Tabs from "./components/Tabs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CoursesProvider>
          <InstancesProvider>
            <Tabs />
            {children}
            <Toaster toastOptions={{
              classNames: {
                success: "bg-green-600 text-white",
                error: "bg-red-600 text-white",
                default: "bg-neutral-800 text-white",
                loading: "bg-black-400 text-white"
              },

              style: { borderRadius: 8, fontSize: 14 },

              // Optional: per-type duration override
              duration: 3000,
            }}/>
          </InstancesProvider>
        </CoursesProvider>
      </body>
    </html>
  );
}
